[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter_dapp = "v8MHshkCyiotq3LWqewLL35j2sUsfVZuobyKd7SMK9s"

[programs.devnet]
counter_dapp = "v8MHshkCyiotq3LWqewLL35j2sUsfVZuobyKd7SMK9s"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
